version: "3"
services:
  devops-influxdb:
    image: influxdb:1.5-alpine
    ports:
      - 8086:8086
    networks:
      - backend
    restart: always
  devops-telegraf:
    image: telegraf:1.6-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - backend
    restart: always
  devops-grafana:
    image: grafana/grafana:5.2.4
    ports:
      - 80:3000
    networks:
      - backend
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=insung
      - GF_SECURITY_ADMIN_PASSWORD=insung

networks:
  backend:
    external: false
